name: yurt_camasirhane
description: A new Flutter project for dormitory laundry management.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  go_router: ^12.0.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  qr_code_scanner: ^1.0.1
  url_launcher: ^6.2.1
  fl_chart: ^0.66.0 # For stats if needed, or just use simple widgets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
